# OSC Checker Configuration
app:
  name: "OSC Checker"
  version: "1.0.0"

sender:
  default_host: "127.0.0.1"
  default_port: 7000
  default_address: "/test"
  window:
    width: 900
    height: 600
    title: "OSC Sender"

receiver:
  default_port: 7000
  window:
    width: 1000
    height: 700
    title: "OSC Receiver"
  max_log_entries: 100
