# OSC Checker Configuration
app:
  name: "OSC Checker"
  version: "1.0.0"

sender:
  list:
    - name: "Local Test"
      host: "127.0.0.1"
      port: 7000
      address: "/test"
      arguments:
        - type: "int"
          default_value: "42"
          description: "Test integer value"
        - type: "float"
          default_value: "3.14"
          description: "Test float value"
        - type: "string"
          default_value: "hello"
          description: "Test string value"
    - name: "Remote Device"
      host: "192.168.1.100"
      port: 9000
      address: "/1/fader1"
      arguments:
        - type: "float"
          default_value: "0.5"
          description: "Fader value (0.0-1.0)"
        - type: "bool"
          default_value: "true"
          description: "Enable flag"
  window:
    width: 900
    height: 600
    title: "OSC Sender"

receiver:
  default_port: 7000
  window:
    width: 1000
    height: 700
    title: "OSC Receiver"
  max_log_entries: 100
