# OSC Checker Configuration
app:
  name: "OSC Checker"
  version: "1.0.0"

sender:
  list:
    - name: "Local Test"
      host: "127.0.0.1"
      port: 7000
      address: "/test"
    - name: "Remote Device"
      host: "192.168.1.100"
      port: 9000
      address: "/1/fader1"
  window:
    width: 900
    height: 600
    title: "OSC Sender"

receiver:
  default_port: 7000
  window:
    width: 1000
    height: 700
    title: "OSC Receiver"
  max_log_entries: 100
