# OSC Checker Settings
# このファイルでconfigファイルのパスを指定します

# config_file: "config.yaml"
# config_file: "config-production.yaml"
# OSC Checker Settings
# このファイルでconfigファイルのパスを指定します

config_file: "config.yaml"

# 他の環境用の設定例（コメントアウト）
# config_file: "config-development.yaml"
# config_file: "config-production.yaml"
# config_file: "config-testing.yaml"
